@echo off
echo Building mrv32
echo Precheck the Resource 
"C:\Program Files (x86)\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" save  "D:\Data\dev\mrv32\mrv32.vcproj"
if not exist arm mkdir arm
if %errorlevel% NEQ 0 goto exit
echo Compiling gccmain.c
"D:\Data\dev\Sourcery_CodeBench_Lite_for_ARM_EABI\bin\arm-none-eabi-gcc" -static -c -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -Ofast -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\Data\dev\mrv32\arm\gccmain.o" -c "C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "D:\Data\dev\mrv32\include" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\ResID" -I "D:\Data\dev\mrv32\src\app\widget" -I "D:\Data\dev\mrv32\src\app\launcher" -I "D:\Data\dev\mrv32\src\app\wallpaper" -I "D:\Data\dev\mrv32\src\app\screen_lock" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\src\framework" -I "D:\Data\dev\mrv32\src\framework\ui_core\base" -I "D:\Data\dev\mrv32\src\framework\ui_core\mvc" -I "D:\Data\dev\mrv32\src\framework\ui_core\pme" -I "D:\Data\dev\mrv32\src\framework\mmi_core" -I "D:\Data\dev\mrv32\src\ui_engine\vrt\interface" -I "D:\Data\dev\mrv32\src\component" -I "D:\Data\dev\mrv32\src\ui_engine\framework\xml" -I "D:\Data\dev\mrv32"
if %errorlevel% NEQ 0 goto exit
echo Compiling Console.cpp
"D:\Data\dev\Sourcery_CodeBench_Lite_for_ARM_EABI\bin\arm-none-eabi-g++" -static -c -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -Ofast -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -fno-rtti -fcheck-new -o "D:\Data\dev\mrv32\arm\Console.o" -c "d:\Data\dev\mrv32\Console.cpp"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "D:\Data\dev\mrv32\include" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\ResID" -I "D:\Data\dev\mrv32\src\app\widget" -I "D:\Data\dev\mrv32\src\app\launcher" -I "D:\Data\dev\mrv32\src\app\wallpaper" -I "D:\Data\dev\mrv32\src\app\screen_lock" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\src\framework" -I "D:\Data\dev\mrv32\src\framework\ui_core\base" -I "D:\Data\dev\mrv32\src\framework\ui_core\mvc" -I "D:\Data\dev\mrv32\src\framework\ui_core\pme" -I "D:\Data\dev\mrv32\src\framework\mmi_core" -I "D:\Data\dev\mrv32\src\ui_engine\vrt\interface" -I "D:\Data\dev\mrv32\src\component" -I "D:\Data\dev\mrv32\src\ui_engine\framework\xml" -I "D:\Data\dev\mrv32"
if %errorlevel% NEQ 0 goto exit
echo Compiling Console_io.cpp 
"D:\Data\dev\Sourcery_CodeBench_Lite_for_ARM_EABI\bin\arm-none-eabi-g++" -static -c -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -Ofast -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -fno-rtti -fcheck-new -fno-rtti -fcheck-new -o "D:\Data\dev\mrv32\arm\Console_io.o" -c "d:\Data\dev\mrv32\Console_io.cpp"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "D:\Data\dev\mrv32\include" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\ResID" -I "D:\Data\dev\mrv32\src\app\widget" -I "D:\Data\dev\mrv32\src\app\launcher" -I "D:\Data\dev\mrv32\src\app\wallpaper" -I "D:\Data\dev\mrv32\src\app\screen_lock" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\src\framework" -I "D:\Data\dev\mrv32\src\framework\ui_core\base" -I "D:\Data\dev\mrv32\src\framework\ui_core\mvc" -I "D:\Data\dev\mrv32\src\framework\ui_core\pme" -I "D:\Data\dev\mrv32\src\framework\mmi_core" -I "D:\Data\dev\mrv32\src\ui_engine\vrt\interface" -I "D:\Data\dev\mrv32\src\component" -I "D:\Data\dev\mrv32\src\ui_engine\framework\xml" -I "D:\Data\dev\mrv32"
if %errorlevel% NEQ 0 goto exit
echo Compiling fifo.c
"D:\Data\dev\Sourcery_CodeBench_Lite_for_ARM_EABI\bin\arm-none-eabi-gcc" -static -c -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -Ofast -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -fno-rtti -fcheck-new -fno-rtti -fcheck-new -o "D:\Data\dev\mrv32\arm\fifo.o" -c "d:\Data\dev\mrv32\fifo.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "D:\Data\dev\mrv32\include" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\ResID" -I "D:\Data\dev\mrv32\src\app\widget" -I "D:\Data\dev\mrv32\src\app\launcher" -I "D:\Data\dev\mrv32\src\app\wallpaper" -I "D:\Data\dev\mrv32\src\app\screen_lock" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\src\framework" -I "D:\Data\dev\mrv32\src\framework\ui_core\base" -I "D:\Data\dev\mrv32\src\framework\ui_core\mvc" -I "D:\Data\dev\mrv32\src\framework\ui_core\pme" -I "D:\Data\dev\mrv32\src\framework\mmi_core" -I "D:\Data\dev\mrv32\src\ui_engine\vrt\interface" -I "D:\Data\dev\mrv32\src\component" -I "D:\Data\dev\mrv32\src\ui_engine\framework\xml" -I "D:\Data\dev\mrv32"
if %errorlevel% NEQ 0 goto exit
echo Compiling main.c 
"D:\Data\dev\Sourcery_CodeBench_Lite_for_ARM_EABI\bin\arm-none-eabi-gcc" -static -c -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -Ofast -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -fno-rtti -fcheck-new -fno-rtti -fcheck-new -o "D:\Data\dev\mrv32\arm\main.o" -c "d:\Data\dev\mrv32\main.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "D:\Data\dev\mrv32\include" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\ResID" -I "D:\Data\dev\mrv32\src\app\widget" -I "D:\Data\dev\mrv32\src\app\launcher" -I "D:\Data\dev\mrv32\src\app\wallpaper" -I "D:\Data\dev\mrv32\src\app\screen_lock" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\src\framework" -I "D:\Data\dev\mrv32\src\framework\ui_core\base" -I "D:\Data\dev\mrv32\src\framework\ui_core\mvc" -I "D:\Data\dev\mrv32\src\framework\ui_core\pme" -I "D:\Data\dev\mrv32\src\framework\mmi_core" -I "D:\Data\dev\mrv32\src\ui_engine\vrt\interface" -I "D:\Data\dev\mrv32\src\component" -I "D:\Data\dev\mrv32\src\ui_engine\framework\xml" -I "D:\Data\dev\mrv32"
if %errorlevel% NEQ 0 goto exit
echo Compiling T2Input.cpp 
"D:\Data\dev\Sourcery_CodeBench_Lite_for_ARM_EABI\bin\arm-none-eabi-g++" -static -c -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -Ofast -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -fno-rtti -fcheck-new -fno-rtti -fcheck-new -fno-rtti -fcheck-new -o "D:\Data\dev\mrv32\arm\T2Input.o" -c "d:\Data\dev\mrv32\T2Input.cpp"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include" -I "C:\Program Files (x86)\MRE SDK V3.0.00\include\service" -I "D:\Data\dev\mrv32\include" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\ResID" -I "D:\Data\dev\mrv32\src\app\widget" -I "D:\Data\dev\mrv32\src\app\launcher" -I "D:\Data\dev\mrv32\src\app\wallpaper" -I "D:\Data\dev\mrv32\src\app\screen_lock" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\include\component" -I "D:\Data\dev\mrv32\include\service" -I "D:\Data\dev\mrv32\src\framework" -I "D:\Data\dev\mrv32\src\framework\ui_core\base" -I "D:\Data\dev\mrv32\src\framework\ui_core\mvc" -I "D:\Data\dev\mrv32\src\framework\ui_core\pme" -I "D:\Data\dev\mrv32\src\framework\mmi_core" -I "D:\Data\dev\mrv32\src\ui_engine\vrt\interface" -I "D:\Data\dev\mrv32\src\component" -I "D:\Data\dev\mrv32\src\ui_engine\framework\xml" -I "D:\Data\dev\mrv32"
if %errorlevel% NEQ 0 goto exit
echo Linking app 
"D:\Data\dev\Sourcery_CodeBench_Lite_for_ARM_EABI\bin\arm-none-eabi-gcc" -s -o "D:\Data\dev\mrv32\mrv32.axf"  "D:\Data\dev\mrv32\arm\gccmain.o"  "D:\Data\dev\mrv32\arm\Console.o"  "D:\Data\dev\mrv32\arm\Console_io.o"  "D:\Data\dev\mrv32\arm\fifo.o"  "D:\Data\dev\mrv32\arm\main.o"  "D:\Data\dev\mrv32\arm\T2Input.o" -Ofast -static -fpic -pie -T "C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc_t\scat.ld" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc_t\percommon.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc_t\pertcp.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc_t\persensor.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc_t\persmsper.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc_t\perbitstream.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc_t\percontact.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc_t\permms.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc_t\persmsmng.a" -l:"C:\Program Files (x86)\MRE SDK V3.0.00\lib\MRE30\armgcc_t\perfile.a"
if %errorlevel% NEQ 0 goto exit
echo Packing resource to app 
"C:\Program Files (x86)\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\Data\dev\mrv32\mrv32.pkd" -e AXF "D:\Data\dev\mrv32\mrv32.vcproj" "D:\Data\dev\mrv32\mrv32.axf"
if %errorlevel% NEQ 0 goto exit
echo Adding tag infromation 
"C:\Program Files (x86)\MRE SDK V3.0.00\tools\PackDigist.exe" "D:\Data\dev\mrv32\mrv32.vcproj" "mrv32" "0.1.0" "mrv32 contributors" "3072" "NotSupportBg" "Not Support rotate" "mrv32" "mrv32" "mrv32" "1234567890" "content" " TCP Sensor SMS(person) BitStream Contact MMS SMSMng File" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "" "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\Data\dev\mrv32\arm D:\Data\dev\mrv32\build.log

:exit
